import { GAME_COLORS } from '../../../config/styles';

export const CONFIG = {
    HEIGHT: 130,
    GAP: 5,

    RARITY_WIDTH: 18,
    RARITY_INDENT_HEIGHT: 40,
    RARITY_IDNENT_OFFEST_X: 5,
    RARITY_IDNENT_OFFEST_Y: 65,

    ITEM_CARD_MAX_WIDTH: 400,
    ITEM_CARD_BACKGROUND: GAME_COLORS.black2,
    ITEM_CARD_BORDER_COLOR: GAME_COLORS.red1,
    ITEM_CARD_BORDER_WIDTH: 1,
    ITEM_CARD_SHARP_OFFSET: 40,

    ITEM_LABEL_COLOR: GAME_COLORS.yellowText.main,
    ITEM_LABEL_FONT_SIZE: 18,
    ITEM_LABEL_FONT_SIZE_PADDING_BOTTOM: 10,
    ITEM_LABEL_LETTER_SPACING: 1,
    ITEM_LABEL_FONT_WEIGHT: 'bold' as 'bolder',

    GUN_SCALE: {
        SNIPER: 0.6,
    },
};