import { GAME_COLORS } from '../../../../const/styles';

export const CONFIG = {
    WIDTH: 700,
    HEIGHT: 950,
    BACKGROUND: GAME_COLORS.black2,
    BORDER_COLOR: GAME_COLORS.red1,
    BORDER_WIDTH: 2,
    SHARP_OFFSET_PRIMARY: 30,
    PROFILE_FRAME_X: 16,
    PROFILE_FRAME_Y: 16,
    ATTRIBUTE_LIST_TITLE_X: Math.floor(700 / 2) + 30,
    ATTRIBUTE_LIST__TITLE_Y: 16,
    ATTRIBUTE_ROW_WIDTH: 305,
    ATTRIBUTES_LIST_X: Math.floor(700 / 2) + 30,
    ATTRIBUTES_LIST_Y: 42,

};

export const PROFILE_CARD_CONFIG = CONFIG;