import { GAME_COLORS } from '../../config/styles';

export const CONFIG = {
    PADDING: 40,
    BACKGROUND: GAME_COLORS.black2,
    BORDER_WIDTH: 2,
    BORDER_COLOR: GAME_COLORS.red1,
    SECTION_WIDTH: 400,
    SECTION_BORDER_WIDTH: 2,
    SECTION_BORDER_COLOR: GAME_COLORS.red1,

    TITLE_SECTION_RARITY_COLOR: GAME_COLORS.red1,
    TITLE_SECTION_RARITY_FONT_SIZE: 18,
    TITLE_SECTION_ITEM_FONT_SIZE: 22,

    DAMAGE_SECTION_MAIN_DAMAGE_FONT_COLOR: GAME_COLORS.red1,
    DAMAGE_SECTION_MAIN_DAMAGE_FONT_SIZE: 28,
    DAMAGE_SECTION_MAIN_DAMAGE_DECIMAL_FONT_SIZE: 22,
    DAMAGE_SECTION_MAIN_DAMAGE_DECIMAL_FONT_Y_OFFSET: 7,
    DAMAGE_SECTION_MAIN_DAMAGE_DECIMAL_FONT_X_OFFSET: -3,
    DAMAGE_SECTION_AMMO_FONT_SIZE: 18,
    DAMAGE_SECTION_AMMO_FONT_COLOR: GAME_COLORS.lightBlue,
    DAMAGE_SECTION_SPECS_MAIN_FONT_SIZE: 20,
    DAMAGE_SECTION_SPECS_SECOND_FONT_SIZE: 16,
    DAMAGE_SECTION_SPECS_FONT_COLOR: GAME_COLORS.white,
};