import { GAME_COLORS } from '../../../../../config/styles';

export const CONFIG = {
    BACKGROUND: GAME_COLORS.black2,
    HEIGHT: 40,
    TEXT_OFFSET_X: 45,
    TEXT_OFFSET_X_WITHOUT_ICON: 10,
    FONT_COLOR: GAME_COLORS.white,
    FONT_SIZE: 22,
    VALUE_FONT_COLOR: GAME_COLORS.white,
    VALUE_FONT_SIZE: 28,
    VALUE_FONT_WEIGHT: 'bolder',
    VALUE_FONT_LETTER_SPACING: 1,
    VALUE_FONT_STROKE_THICKNESS: 2,
    VALUE_FONT_STROKE: GAME_COLORS.red1,
};